"""
integrations/github_issue.py — GitHub Issues adapter.

Creates GitHub issues via the REST API using a fine-grained PAT.
Labels applied: eaa-finding, severity-<sev>, module-<module>.

Env vars:
    EAA_GITHUB_ISSUE_REPO   owner/repo, e.g. myorg/enterprise-ai-accelerator
    EAA_GITHUB_ISSUE_TOKEN  fine-grained PAT with Issues: read/write permission
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from integrations.base import Finding, IntegrationAdapter, IntegrationResult

logger = logging.getLogger(__name__)

_GITHUB_API = "https://api.github.com"
_ACCEPT_HEADER = "application/vnd.github+json"
_API_VERSION = "2022-11-28"


def _build_body(finding: Finding) -> str:
    lines = [
        f"## {finding.title}",
        "",
        finding.description,
        "",
        "### Details",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Severity** | `{finding.severity.upper()}` |",
        f"| **Module** | `{finding.module}` |",
    ]
    if finding.resource_id:
        lines.append(f"| **Resource** | `{finding.resource_id}` |")
    if finding.tags:
        lines.append(f"| **Tags** | {', '.join(f'`{t}`' for t in finding.tags)} |")
    lines.append(f"| **Finding ID** | `{finding.id}` |")
    lines.append(f"| **Detected** | `{finding.created_at.strftime('%Y-%m-%d %H:%M UTC')}` |")

    if finding.remediation:
        lines.extend([
            "",
            "### Remediation",
            "",
            finding.remediation,
        ])

    if finding.metadata:
        lines.extend([
            "",
            "<details>",
            "<summary>Raw metadata</summary>",
            "",
            "```json",
        ])
        import json
        lines.append(json.dumps(finding.metadata, indent=2, default=str))
        lines.extend(["```", "", "</details>"])

    lines.extend([
        "",
        "---",
        "*Generated by [enterprise-ai-accelerator](https://github.com/search?q=enterprise-ai-accelerator)*",
    ])
    return "\n".join(lines)


class GitHubIssueAdapter(IntegrationAdapter):
    """
    Creates a GitHub issue for each finding via the GitHub REST API.

    Args:
        repo:      owner/repo slug, e.g. "myorg/enterprise-ai-accelerator"
        token:     Fine-grained PAT or classic PAT with repo scope.
        labels_extra: Additional labels to attach beyond the auto-generated ones.
        dry_run:   Return success without HTTP calls.
        timeout:   HTTP timeout seconds.
    """

    name = "github_issue"

    def __init__(
        self,
        repo: str,
        token: str,
        labels_extra: list[str] | None = None,
        dry_run: bool = False,
        timeout: float = 15.0,
    ) -> None:
        if "/" not in repo:
            raise ValueError(f"repo must be 'owner/repo', got {repo!r}")
        self.repo = repo
        self.labels_extra = labels_extra or []
        self.dry_run = dry_run
        self.timeout = timeout
        self._headers = {
            "Authorization": f"Bearer {token}",
            "Accept": _ACCEPT_HEADER,
            "X-GitHub-Api-Version": _API_VERSION,
        }

    def _build_labels(self, finding: Finding) -> list[str]:
        labels = [
            "eaa-finding",
            f"severity-{finding.severity}",
            f"module-{finding.module}",
        ]
        labels.extend(self.labels_extra)
        return labels

    async def _ensure_labels(
        self, client: httpx.AsyncClient, labels: list[str]
    ) -> None:
        """Create missing labels so the issue creation doesn't fail."""
        color_map = {
            "severity-critical": "CC0000",
            "severity-high":     "E03E2D",
            "severity-medium":   "F0A500",
            "severity-low":      "F5D020",
            "severity-info":     "A0A0A0",
            "eaa-finding":       "0052CC",
        }
        url = f"{_GITHUB_API}/repos/{self.repo}/labels"
        for label in labels:
            color = color_map.get(label, "EDEDED")
            payload: dict[str, Any] = {"name": label, "color": color}
            try:
                r = await client.post(url, json=payload, headers=self._headers)
                # 422 = already exists — that's fine
                if r.status_code not in (201, 422):
                    logger.debug("Label create %s → HTTP %s", label, r.status_code)
            except Exception:
                pass  # Label errors never block issue creation

    async def send(self, finding: Finding) -> IntegrationResult:
        if self.dry_run:
            return IntegrationResult.dry(f"github-issue:{finding.id}", adapter=self.name)

        url = f"{_GITHUB_API}/repos/{self.repo}/issues"
        labels = self._build_labels(finding)
        title = f"[{finding.severity.upper()}] {finding.title}"[:256]

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                await self._ensure_labels(client, labels)
                response = await client.post(
                    url,
                    json={
                        "title": title,
                        "body": _build_body(finding),
                        "labels": labels,
                    },
                    headers=self._headers,
                )
                response.raise_for_status()
                data = response.json()
        except httpx.HTTPStatusError as exc:
            body = exc.response.text[:300]
            msg = f"GitHub HTTP {exc.response.status_code}: {body}"
            logger.error("GitHubIssueAdapter: %s", msg)
            return IntegrationResult.failure(msg, adapter=self.name)
        except Exception as exc:
            logger.error("GitHubIssueAdapter unexpected error: %s", exc)
            return IntegrationResult.failure(str(exc), adapter=self.name)

        html_url = data.get("html_url", "")
        number = data.get("number", "")
        logger.info("GitHubIssueAdapter: created issue #%s", number)
        return IntegrationResult.success(html_url, adapter=self.name)
