"""
Jira Integration — Create tickets from analysis findings.

Usage:
    from integrations.jira_creator import JiraCreator
    jira = JiraCreator(
        server=os.getenv("JIRA_SERVER"),
        email=os.getenv("JIRA_EMAIL"),
        api_token=os.getenv("JIRA_API_TOKEN"),
        project_key=os.getenv("JIRA_PROJECT_KEY")
    )
    tickets = jira.create_from_compliance(compliance_result)
"""

import os
from typing import Optional


class JiraCreator:
    def __init__(self,
                 server: Optional[str] = None,
                 email: Optional[str] = None,
                 api_token: Optional[str] = None,
                 project_key: Optional[str] = None):
        self.server = server or os.getenv("JIRA_SERVER")
        self.email = email or os.getenv("JIRA_EMAIL")
        self.api_token = api_token or os.getenv("JIRA_API_TOKEN")
        self.project_key = project_key or os.getenv("JIRA_PROJECT_KEY")
    
    def create_from_compliance(self, compliance_result) -> list[str]:
        """
        Create Jira tickets for each critical and high compliance violation.
        Returns list of created ticket keys.
        """
        if not all([self.server, self.email, self.api_token, self.project_key]):
            print("Jira not configured — set JIRA_SERVER, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY")
            return []
        
        try:
            from jira import JIRA
        except ImportError:
            print("Install jira: pip install jira")
            return []
        
        client = JIRA(self.server, basic_auth=(self.email, self.api_token))
        created = []
        
        priority_map = {"CRITICAL": "Highest", "HIGH": "High", "MEDIUM": "Medium", "LOW": "Low"}
        
        for violation in compliance_result.critical_violations + compliance_result.high_violations:
            issue = client.create_issue({
                "project": {"key": self.project_key},
                "summary": f"[{violation.framework} {violation.control_id}] {violation.finding[:80]}",
                "description": (
                    f"*Resource:* {violation.resource}\n\n"
                    f"*Finding:* {violation.finding}\n\n"
                    f"*Remediation:* {violation.remediation}\n\n"
                    f"*Terraform Fix:*\n{{code}}{violation.terraform_fix}{{code}}\n\n"
                    f"_Generated by enterprise-ai-accelerator PolicyGuard_"
                ),
                "issuetype": {"name": "Task"},
                "priority": {"name": priority_map.get(violation.severity, "Medium")},
                "labels": ["cloud-compliance", "security", violation.framework.lower()]
            })
            created.append(issue.key)
        
        return created
    
    def create_from_cost(self, cost_result) -> list[str]:
        """Create Jira tickets for cost optimization quick wins."""
        if not all([self.server, self.email, self.api_token, self.project_key]):
            return []
        
        try:
            from jira import JIRA
        except ImportError:
            return []
        
        client = JIRA(self.server, basic_auth=(self.email, self.api_token))
        created = []
        
        for finding in cost_result.quick_wins:
            issue = client.create_issue({
                "project": {"key": self.project_key},
                "summary": f"[Cost] {finding.action[:80]} — ${finding.savings_monthly:,.0f}/mo",
                "description": (
                    f"*Category:* {finding.category}\n"
                    f"*Resource:* {finding.resource}\n\n"
                    f"*Current Cost:* ${finding.current_monthly:,.0f}/month\n"
                    f"*Optimized Cost:* ${finding.optimized_monthly:,.0f}/month\n"
                    f"*Monthly Savings:* ${finding.savings_monthly:,.0f} ({finding.savings_pct:.1f}%)\n"
                    f"*Annual Savings:* ${finding.savings_monthly * 12:,.0f}\n\n"
                    f"*Action Required:* {finding.action}\n\n"
                    f"*Implementation Risk:* {finding.risk}\n"
                    f"*Estimated Effort:* {finding.effort}\n"
                    f"*Payback Period:* {finding.payback_days} days\n\n"
                    f"_Generated by enterprise-ai-accelerator CostAnalyzer_"
                ),
                "issuetype": {"name": "Task"},
                "priority": {"name": "High" if finding.savings_monthly > 1000 else "Medium"},
                "labels": ["cloud-cost", "finops", finding.category.lower()]
            })
            created.append(issue.key)
        
        return created
