"""
runbook_generator.py — AI-Powered Migration Runbook Generator
==============================================================

V2: Updated for MigrationScout V2. Uses claude-sonnet-4-6.
    Added generate_workload_runbook() for API usage.
    Pyramid Principle executive framing in AI prompt.

Generates detailed, wave-specific migration runbooks using Claude Sonnet.
Each runbook is tailored to the workload type and migration strategy.

Runbook structure per workload:
  1. Pre-migration checklist
  2. Environment preparation steps
  3. Migration execution steps (strategy-specific)
  4. Validation and smoke tests
  5. Cutover procedure
  6. Rollback procedure
  7. Post-migration checklist

Exports as Markdown files (one per wave).
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

import anthropic
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn

from .assessor import WorkloadAssessment, MigrationStrategy
from .wave_planner import MigrationWave, WavePlan

console = Console()


@dataclass
class RunbookStep:
    """A single step in a migration runbook."""
    step_number: int
    title: str
    description: str
    commands: list[str] = field(default_factory=list)
    validation: str = ""
    estimated_minutes: int = 15
    responsible_role: str = "Cloud Engineer"
    is_critical: bool = False


@dataclass
class MigrationRunbook:
    """Complete runbook for migrating a single workload."""
    workload_id: str
    workload_name: str
    strategy: MigrationStrategy
    target_service: str
    pre_migration_checklist: list[str]
    migration_steps: list[RunbookStep]
    validation_tests: list[str]
    rollback_procedure: list[str]
    post_migration_checklist: list[str]
    estimated_total_hours: float
    ai_generated: bool = False
    generated_at: str = ""

    def to_markdown(self) -> str:
        """Render the runbook as Markdown."""
        lines = [
            f"# Migration Runbook: {self.workload_name}",
            "",
            f"> **Strategy:** {self.strategy.value}  ",
            f"> **Target:** {self.target_service}  ",
            f"> **Estimated Duration:** {self.estimated_total_hours:.1f} hours  ",
            f"> **Generated:** {self.generated_at}  ",
            "",
            "---",
            "",
            "## Pre-Migration Checklist",
            "",
        ]

        for i, item in enumerate(self.pre_migration_checklist, 1):
            lines.append(f"- [ ] {item}")

        lines += ["", "---", "", "## Migration Steps", ""]

        for step in self.migration_steps:
            critical_badge = " [CRITICAL]" if step.is_critical else ""
            lines.append(f"### Step {step.step_number}: {step.title}{critical_badge}")
            lines.append(f"**Role:** {step.responsible_role} | **Est. Time:** {step.estimated_minutes} min")
            lines.append("")
            lines.append(step.description)

            if step.commands:
                lines.append("")
                lines.append("```bash")
                for cmd in step.commands:
                    lines.append(cmd)
                lines.append("```")

            if step.validation:
                lines.append("")
                lines.append(f"**Validation:** {step.validation}")

            lines.append("")

        lines += ["---", "", "## Validation Tests", ""]
        for test in self.validation_tests:
            lines.append(f"- [ ] {test}")

        lines += ["", "---", "", "## Cutover Procedure", ""]
        lines.append("1. Confirm all validation tests pass")
        lines.append("2. Schedule cutover window with stakeholders (prefer off-peak hours)")
        lines.append("3. Send cutover notification to dependent teams")
        lines.append("4. Execute DNS/load balancer cutover")
        lines.append("5. Monitor for 30 minutes post-cutover")
        lines.append("6. Send all-clear notification")

        lines += ["", "---", "", "## Rollback Procedure", ""]
        for i, step in enumerate(self.rollback_procedure, 1):
            lines.append(f"{i}. {step}")

        lines += ["", "---", "", "## Post-Migration Checklist", ""]
        for item in self.post_migration_checklist:
            lines.append(f"- [ ] {item}")

        lines += ["", "---", "", "*Runbook generated by MigrationScout v2.0.0*"]

        return "\n".join(lines)


@dataclass
class WaveRunbook:
    """Collection of runbooks for a single migration wave."""
    wave: MigrationWave
    runbooks: list[MigrationRunbook]
    wave_kickoff_checklist: list[str]
    wave_completion_checklist: list[str]

    def to_markdown(self) -> str:
        """Render the wave runbook as Markdown."""
        lines = [
            f"# Wave {self.wave.wave_number + 1} Migration Runbook: {self.wave.name}",
            "",
            f"> **Workloads:** {self.wave.workload_count}  ",
            f"> **Estimated Duration:** {self.wave.estimated_duration_weeks:.1f} weeks  ",
            f"> **Risk Level:** {self.wave.risk_level.upper()}  ",
            f"> **Migration Cost:** ${self.wave.total_migration_cost_usd:,.0f}  ",
            "",
            "---",
            "",
            "## Wave Kickoff Checklist",
            "",
        ]

        for item in self.wave_kickoff_checklist:
            lines.append(f"- [ ] {item}")

        lines += ["", "---", ""]

        for runbook in self.runbooks:
            lines.append(runbook.to_markdown())
            lines.append("")
            lines.append("---")
            lines.append("")

        lines += ["## Wave Completion Checklist", ""]
        for item in self.wave_completion_checklist:
            lines.append(f"- [ ] {item}")

        return "\n".join(lines)


# Strategy-specific template steps (fallback when AI is unavailable)
_TEMPLATE_STEPS: dict[MigrationStrategy, list[tuple[str, str, list[str], int]]] = {
    MigrationStrategy.REHOST: [
        ("Inventory Validation", "Validate server specs, OS version, and installed software against migration plan",
         ["aws-cli ec2 describe-instances --region us-east-1",
          "# Document: CPU, RAM, disk, OS, installed packages"], 30),
        ("AWS MGN Agent Installation", "Install AWS Application Migration Service replication agent on source server",
         ["wget -O ./aws-replication-installer-init.py https://aws-replication-installer-init.us-east-1.s3.amazonaws.com/latest/linux/aws-replication-installer-init.py",
          "sudo python3 aws-replication-installer-init.py --region us-east-1 --aws-access-key-id $AWS_ACCESS_KEY_ID --aws-secret-access-key $AWS_SECRET_ACCESS_KEY"], 45),
        ("Initial Replication", "Wait for initial data replication to complete (can take 2-24 hours for large volumes)",
         ["# Monitor replication status in AWS MGN console",
          "# Target: 'Ready for testing' status"], 60),
        ("Launch Test Instance", "Launch a test instance and validate functionality",
         ["# Via AWS MGN console: Launch test instances",
          "# Or via CLI: aws mgn start-test --source-server-ids srv-xxxxxxxx"], 30),
        ("Cutover", "Stop source server replication lag to near-zero, then launch cutover instance",
         ["# AWS MGN console: Mark as ready for cutover",
          "aws mgn start-cutover --source-server-ids srv-xxxxxxxx"], 30),
    ],
    MigrationStrategy.REPLATFORM: [
        ("Containerization Assessment", "Analyze application for containerization readiness",
         ["# Check for hardcoded configs, local file system dependencies",
          "# Document environment variables and external service connections"], 60),
        ("Dockerfile Creation", "Create optimized Dockerfile for the application",
         ["# Create Dockerfile based on application requirements",
          "docker build -t app-name:latest .",
          "docker run -p 8080:8080 app-name:latest"], 90),
        ("ECS Task Definition", "Define ECS Fargate task definition and service",
         ["aws ecs register-task-definition --cli-input-json file://task-definition.json",
          "aws ecs create-service --cluster prod-cluster --service-name app-service --task-definition app-task:1 --desired-count 2 --launch-type FARGATE"], 45),
        ("Load Balancer Configuration", "Configure ALB target group and listener rules",
         ["aws elbv2 create-target-group --name app-tg --protocol HTTP --port 8080 --vpc-id vpc-xxxxxxxx --target-type ip",
          "aws elbv2 register-targets --target-group-arn arn:aws:elasticloadbalancing:... --targets Id=<ip>"], 30),
        ("DNS Cutover", "Update DNS to point to ALB and validate",
         ["# Update Route 53 record to ALB DNS name",
          "aws route53 change-resource-record-sets --hosted-zone-id ZXXXXXXXX --change-batch file://dns-change.json"], 15),
    ],
    MigrationStrategy.REFACTOR: [
        ("Architecture Design Review", "Review and finalize target microservices architecture",
         ["# Document service boundaries, APIs, data stores",
          "# Create architecture diagram in draw.io or Lucidchart"], 120),
        ("Infrastructure as Code Setup", "Initialize Terraform workspace and write core infrastructure",
         ["terraform init",
          "terraform plan -out=migration.tfplan",
          "terraform apply migration.tfplan"], 180),
        ("CI/CD Pipeline Creation", "Set up deployment pipeline for new services",
         ["# Create GitHub Actions workflow or CodePipeline",
          "# Configure ECR repository for container images",
          "aws ecr create-repository --repository-name service-name"], 90),
        ("Data Migration", "Migrate data to target store (RDS, DynamoDB, etc.)",
         ["# Use AWS DMS for database migration",
          "aws dms create-replication-task --replication-task-identifier migrate-db ...",
          "# Validate row counts and data integrity"], 120),
        ("Parallel Run & Traffic Shifting", "Run old and new systems in parallel, gradually shift traffic",
         ["# Configure weighted routing in Route 53 or ALB",
          "# Start: 10% traffic to new, 90% to old",
          "# Monitor error rates before increasing"], 60),
    ],
    MigrationStrategy.REPURCHASE: [
        ("SaaS Vendor Evaluation", "Finalize SaaS vendor selection and commercial terms",
         ["# Complete vendor security review",
          "# Sign MSA and order form",
          "# Obtain test/sandbox environment"], 240),
        ("Data Export", "Export data from legacy system for migration to SaaS",
         ["# Export in standard format (CSV, XML, JSON)",
          "# Validate export completeness",
          "# Encrypt sensitive data for transfer"], 120),
        ("SaaS Configuration", "Configure SaaS platform with org-specific settings",
         ["# Set up SSO/SAML integration",
          "# Configure workflows and permissions",
          "# Import reference data"], 180),
        ("Data Import", "Import historical data into SaaS platform",
         ["# Use SaaS import tool or API",
          "# Validate record counts match source",
          "# Test key workflows with imported data"], 90),
        ("User Training & Cutover", "Train users and execute cutover",
         ["# Conduct training sessions for end users",
          "# Set legacy system to read-only",
          "# Enable SaaS system as primary"], 60),
    ],
    MigrationStrategy.RETIRE: [
        ("Dependency Confirmation", "Confirm no active users or systems depend on this workload",
         ["# Pull last 90 days of access logs",
          "# Survey application owners",
          "# Check monitoring for active connections"], 60),
        ("Data Archival", "Archive any data required for compliance or future reference",
         ["# Export data to S3 Glacier (long-term archive)",
          "aws s3 cp /data s3://archive-bucket/workload-name/ --recursive --storage-class GLACIER"], 45),
        ("License Termination", "Cancel software licenses and maintenance contracts",
         ["# Notify vendor to cancel license",
          "# Retrieve any license keys for inventory"], 30),
        ("Server Decommission", "Shut down and decommission servers",
         ["# Graceful shutdown",
          "sudo shutdown -h now",
          "# Remove from monitoring, CMDB, DNS"], 30),
    ],
    MigrationStrategy.RETAIN: [
        ("Document Retain Decision", "Record the reason for retaining on-premises",
         ["# Document: compliance requirement / custom hardware / timeline",
          "# Set review date (6-12 months)"], 30),
        ("Network Connectivity Validation", "Ensure hybrid connectivity for cloud-migrated dependencies",
         ["# Verify VPN or Direct Connect bandwidth",
          "aws ec2 describe-vpn-connections",
          "# Test latency to retained system from cloud workloads"], 45),
        ("Monitoring Integration", "Integrate on-premises monitoring with cloud observability",
         ["# Install CloudWatch agent if applicable",
          "# Set up synthetic monitoring from cloud"], 60),
    ],
}


def _build_template_runbook(a: WorkloadAssessment) -> MigrationRunbook:
    """Build a template-based runbook when AI is unavailable."""
    template = _TEMPLATE_STEPS.get(a.strategy, _TEMPLATE_STEPS[MigrationStrategy.REHOST])
    steps: list[RunbookStep] = []

    for i, (title, desc, cmds, mins) in enumerate(template, 1):
        steps.append(RunbookStep(
            step_number=i,
            title=title,
            description=desc,
            commands=cmds,
            estimated_minutes=mins,
            is_critical=(i == 1 or i == len(template)),
        ))

    pre_checklist = [
        "Backup confirmation: full backup completed and verified",
        "Stakeholder notification sent (at least 48hr in advance)",
        "Rollback plan documented and reviewed",
        "Team availability confirmed for migration window",
        "All dependencies identified and owners notified",
        "Monitoring dashboards open and baselines recorded",
        "On-call escalation path documented",
    ]

    validation_tests = [
        f"Application URL returns HTTP 200",
        f"Core workflow end-to-end test passes",
        f"Database connectivity verified",
        f"Performance baseline within 20% of pre-migration",
        f"Security group ingress/egress validated",
        f"Logging and monitoring active in CloudWatch",
        f"Backup policy applied to new resources",
    ]

    rollback = [
        "Assess severity and make go/no-go decision (within 15 minutes of issue detection)",
        "Notify stakeholders of rollback initiation",
        "Revert DNS to point to original on-premises system",
        "Verify on-premises system health and traffic acceptance",
        "Stop cloud resources (do not delete — needed for post-mortem)",
        "Conduct rollback retrospective within 24 hours",
        "Document root cause and update runbook before re-attempt",
    ]

    post_checklist = [
        "Verify all monitoring alerts configured",
        "Confirm backup schedule active",
        "Update CMDB with new cloud resource IDs",
        "Remove on-premises firewall rules pointing to migrated app",
        "Schedule on-premises server decommission (allow 2-week parallel run)",
        "Update DNS TTL to normal (from 60s to 3600s)",
        "Close migration ticket and notify stakeholders",
    ]

    return MigrationRunbook(
        workload_id=a.workload.id,
        workload_name=a.workload.name,
        strategy=a.strategy,
        target_service=a.target_service,
        pre_migration_checklist=pre_checklist,
        migration_steps=steps,
        validation_tests=validation_tests,
        rollback_procedure=rollback,
        post_migration_checklist=post_checklist,
        estimated_total_hours=sum(s.estimated_minutes for s in steps) / 60.0,
        ai_generated=False,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
    )


def _parse_ai_runbook(raw_text: str, a: WorkloadAssessment) -> MigrationRunbook:
    """Parse AI-generated runbook text into structured MigrationRunbook."""
    # Use the AI text as-is for the migration steps description
    # Parse sections by heading markers
    sections: dict[str, list[str]] = {}
    current_section = "intro"
    sections[current_section] = []

    for line in raw_text.split("\n"):
        if line.startswith("##"):
            current_section = line.lstrip("#").strip().lower()
            sections[current_section] = []
        else:
            sections.setdefault(current_section, []).append(line)

    def extract_checklist(section_key: str) -> list[str]:
        items = []
        for line in sections.get(section_key, []):
            line = line.strip()
            if line.startswith(("- ", "* ", "[ ] ")):
                item = line.lstrip("-*[ ]").strip()
                if item:
                    items.append(item)
            elif line and line[0].isdigit() and "." in line[:3]:
                item = line.split(".", 1)[-1].strip()
                if item:
                    items.append(item)
        return items or [f"Refer to AI-generated runbook for {section_key} items"]

    # Build steps from AI output
    migration_text = "\n".join(
        sections.get("migration steps", [])
        or sections.get("migration execution steps", [])
        or sections.get("steps", [])
    )

    steps: list[RunbookStep] = []
    current_step_lines: list[str] = []
    step_num = 1

    for line in migration_text.split("\n"):
        if line.strip().startswith(("### Step", "**Step ")):
            if current_step_lines:
                steps.append(RunbookStep(
                    step_number=step_num - 1,
                    title=f"Migration Step {step_num - 1}",
                    description="\n".join(current_step_lines[:3]),
                    commands=[l.strip().lstrip("- ") for l in current_step_lines if l.strip().startswith("`")],
                    estimated_minutes=30,
                ))
                current_step_lines = []
        elif line.strip():
            current_step_lines.append(line.strip())
            step_num += 1

    if not steps:
        # Fall back to a single step with all the AI content
        steps = [RunbookStep(
            step_number=1,
            title="AI-Generated Migration Steps",
            description=migration_text[:1000] if migration_text else "See full AI runbook content.",
            estimated_minutes=120,
            is_critical=True,
        )]

    pre = extract_checklist("pre-migration checklist")
    validation = extract_checklist("validation tests")
    rollback = extract_checklist("rollback procedure")
    post = extract_checklist("post-migration checklist")

    total_hours = sum(s.estimated_minutes for s in steps) / 60.0 or 4.0

    return MigrationRunbook(
        workload_id=a.workload.id,
        workload_name=a.workload.name,
        strategy=a.strategy,
        target_service=a.target_service,
        pre_migration_checklist=pre or ["Backup completed", "Team notified", "Rollback plan ready"],
        migration_steps=steps,
        validation_tests=validation or ["Application health check passes", "Core workflows validated"],
        rollback_procedure=rollback or ["Revert DNS", "Restore from backup", "Notify stakeholders"],
        post_migration_checklist=post or ["Update CMDB", "Configure monitoring", "Decommission source"],
        estimated_total_hours=total_hours,
        ai_generated=True,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
    )


@dataclass
class RunbookResult:
    """Lightweight result struct for API usage (POST /runbooks/{id})."""
    content: str
    estimated_hours: float
    risk_level: str
    ai_generated: bool


def _risk_level_from_assessment(a: WorkloadAssessment) -> str:
    """Map risk_score (0-100) to low/medium/high/critical."""
    score = getattr(a, "risk_score", 50)
    if score >= 75:
        return "critical"
    if score >= 55:
        return "high"
    if score >= 35:
        return "medium"
    return "low"


class RunbookGenerator:
    """
    Generates migration runbooks using Claude Sonnet.
    Falls back to template-based generation when AI is unavailable.
    """

    def __init__(self, use_ai: bool = True) -> None:
        self.use_ai = use_ai
        self._client: anthropic.Anthropic | None = None

        if self.use_ai:
            api_key = os.environ.get("ANTHROPIC_API_KEY")
            if api_key:
                self._client = anthropic.Anthropic(api_key=api_key)
            else:
                console.print("[yellow]ANTHROPIC_API_KEY not set — using template-based runbooks[/yellow]")
                self.use_ai = False

    def _ai_generate_runbook(self, a: WorkloadAssessment) -> MigrationRunbook:
        """Call Claude Sonnet to generate a detailed, workload-specific runbook."""
        if not self._client:
            return _build_template_runbook(a)

        prompt = f"""You are a senior cloud migration architect writing a detailed migration runbook.

WORKLOAD: {a.workload.name}
Type: {a.workload.workload_type}
Stack: {a.workload.language}/{a.workload.framework} on {a.workload.os}
Migration Strategy: {a.strategy.value}
Target Service: {a.target_service}
Complexity: {a.complexity.value}
Risk Score: {a.risk_score}/100
Business Criticality: {a.workload.business_criticality}
Notes: {a.workload.notes or 'None'}
AI Assessment: {a.ai_rationale}

Write a complete, detailed migration runbook with these EXACT sections:

## Pre-Migration Checklist
(10-12 items as bullet points - [ ] format)

## Migration Execution Steps
(5-7 numbered steps, each with shell commands where applicable)

## Validation Tests
(8-10 items as bullet points - [ ] format)

## Rollback Procedure
(6-8 steps as numbered list)

## Post-Migration Checklist
(8-10 items as bullet points - [ ] format)

Be specific to this workload type and strategy. Include real AWS CLI commands where applicable.
Keep each section concise but actionable. Total response should be ~800 words."""

        try:
            response = self._client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )
            raw_text = response.content[0].text
            return _parse_ai_runbook(raw_text, a)
        except Exception as exc:
            console.print(f"[yellow]AI runbook failed for {a.workload.name}: {exc} — using template[/yellow]")
            return _build_template_runbook(a)

    def generate_runbook(self, a: WorkloadAssessment) -> MigrationRunbook:
        """Generate a runbook for a single workload."""
        if self.use_ai:
            return self._ai_generate_runbook(a)
        return _build_template_runbook(a)

    def generate_workload_runbook(self, a: WorkloadAssessment) -> "RunbookResult":
        """
        Generate a runbook for API usage. Returns a simple RunbookResult.
        Used by api.py POST /runbooks/{workload_id}.
        """
        runbook = self.generate_runbook(a)
        return RunbookResult(
            content=runbook.to_markdown(),
            estimated_hours=runbook.estimated_total_hours,
            risk_level=_risk_level_from_assessment(a),
            ai_generated=runbook.ai_generated,
        )

    def generate_wave_runbook(
        self,
        wave: MigrationWave,
        assessments: list[WorkloadAssessment],
        show_progress: bool = True,
    ) -> WaveRunbook:
        """Generate runbooks for all workloads in a wave."""
        wave_assessments = [a for a in assessments if a.workload.id in wave.workload_ids]
        runbooks: list[MigrationRunbook] = []

        if show_progress:
            with Progress(
                SpinnerColumn(),
                TextColumn(f"[bold blue]Generating Wave {wave.wave_number + 1} runbooks..."),
                BarColumn(),
                TaskProgressColumn(),
                console=console,
            ) as progress:
                task = progress.add_task("", total=len(wave_assessments))
                for a in wave_assessments:
                    runbooks.append(self.generate_runbook(a))
                    progress.advance(task)
        else:
            runbooks = [self.generate_runbook(a) for a in wave_assessments]

        kickoff_checklist = [
            f"Wave {wave.wave_number + 1} go/no-go meeting completed",
            "All wave workload owners confirmed available",
            "Rollback decision criteria documented and agreed",
            "Monitoring dashboards configured for all wave workloads",
            "Communication channel (Slack/Teams) created for wave team",
            "Cloud resources pre-provisioned and validated",
            "Network connectivity tests passed (VPN/Direct Connect)",
            "Change management ticket approved",
            f"Wave budget confirmed: ${wave.total_migration_cost_usd:,.0f}",
        ]

        completion_checklist = [
            f"All {wave.workload_count} workloads migrated and validated",
            "Source systems operating in read-only parallel mode",
            "Monitoring baselines established for all migrated workloads",
            "Cost tracking tags applied to all new cloud resources",
            "Wave retrospective meeting scheduled",
            f"Monthly savings target validated: ${wave.total_monthly_savings_usd:,.0f}/mo",
            "Next wave kickoff scheduled",
            "Wave completion report sent to stakeholders",
        ]

        return WaveRunbook(
            wave=wave,
            runbooks=runbooks,
            wave_kickoff_checklist=kickoff_checklist,
            wave_completion_checklist=completion_checklist,
        )

    def generate_all_wave_runbooks(
        self,
        plan: WavePlan,
        assessments: list[WorkloadAssessment],
        output_dir: str | None = None,
        show_progress: bool = True,
    ) -> list[WaveRunbook]:
        """
        Generate runbooks for all waves in a plan.

        If output_dir is provided, exports Markdown files to that directory.
        """
        wave_runbooks: list[WaveRunbook] = []

        console.print(f"\n[bold blue]Generating migration runbooks for {len(plan.waves)} waves...[/bold blue]")
        if self.use_ai:
            console.print("[dim]Using Claude Sonnet for AI-powered runbook generation[/dim]")
        else:
            console.print("[dim]Using template-based runbook generation[/dim]")

        for wave in plan.waves:
            console.print(f"\n[bold]Wave {wave.wave_number + 1}: {wave.name}[/bold] ({wave.workload_count} workloads)")
            wave_runbook = self.generate_wave_runbook(wave, assessments, show_progress=show_progress)
            wave_runbooks.append(wave_runbook)

        if output_dir:
            self._export_runbooks(wave_runbooks, output_dir)

        total_runbooks = sum(len(wr.runbooks) for wr in wave_runbooks)
        console.print(
            Panel(
                f"  Runbooks generated:   [bold white]{total_runbooks}[/bold white]\n"
                f"  Waves covered:        [bold white]{len(wave_runbooks)}[/bold white]\n"
                f"  AI-generated:         [bold cyan]{'Yes' if self.use_ai else 'No (template-based)'}[/bold cyan]"
                + (f"\n  Output directory:     [bold green]{output_dir}[/bold green]" if output_dir else ""),
                title="[bold]Runbook Generation Complete[/bold]",
                border_style="green",
            )
        )

        return wave_runbooks

    def _export_runbooks(self, wave_runbooks: list[WaveRunbook], output_dir: str) -> None:
        """Export all runbooks as Markdown files."""
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        for wr in wave_runbooks:
            filename = f"wave_{wr.wave.wave_number + 1:02d}_{wr.wave.name.lower().replace(' ', '_')}_runbook.md"
            file_path = output_path / filename
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(wr.to_markdown())
            console.print(f"  [green]Exported:[/green] {file_path}")
