"""
integrations/confluence.py — Confluence Cloud Integration
==========================================================

Publishes migration runbooks as Confluence pages.
Supports Confluence Cloud REST API v2.

Environment variables:
  CONFLUENCE_URL     — e.g., "https://company.atlassian.net/wiki"
  CONFLUENCE_EMAIL   — Atlassian user email
  CONFLUENCE_TOKEN   — Atlassian API token
  CONFLUENCE_SPACE   — Space key, e.g., "CLOUDMIG"
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from rich.console import Console

console = Console()


@dataclass
class ConfluencePage:
    page_id: str
    title: str
    url: str
    space_key: str
    dry_run: bool = False

    def __str__(self) -> str:
        prefix = "[DRY RUN] " if self.dry_run else ""
        return f"{prefix}Confluence page: {self.title} ({self.url})"


class ConfluenceClient:
    """
    Confluence Cloud REST API client.

    Creates:
    - Parent page: "Cloud Migration Project — [Project Name]"
    - Child page per wave: Wave N Runbook
    - Child page per workload: individual runbook pages
    - Index page with links to all runbooks and status table

    Dry-run mode works without any credentials.
    """

    def __init__(
        self,
        url: str | None = None,
        email: str | None = None,
        token: str | None = None,
        space_key: str | None = None,
    ) -> None:
        self.url = (url or os.environ.get("CONFLUENCE_URL", "https://demo.atlassian.net/wiki")).rstrip("/")
        self.email = email or os.environ.get("CONFLUENCE_EMAIL", "")
        self.token = token or os.environ.get("CONFLUENCE_TOKEN", "")
        self.space_key = space_key or os.environ.get("CONFLUENCE_SPACE", "CLOUDMIG")

    @property
    def _dry_run(self) -> bool:
        return not (self.email and self.token)

    def _create_page(
        self,
        title: str,
        body_html: str,
        parent_id: str | None = None,
    ) -> dict[str, Any]:
        """Create a Confluence page. Returns simulated response in dry-run mode."""
        if self._dry_run:
            return self._simulate_page(title)

        payload: dict[str, Any] = {
            "type": "page",
            "title": title,
            "space": {"key": self.space_key},
            "body": {"storage": {"value": body_html, "representation": "storage"}},
        }
        if parent_id:
            payload["ancestors"] = [{"id": parent_id}]

        try:
            import requests
            resp = requests.post(
                f"{self.url}/rest/api/content",
                json=payload,
                auth=(self.email, self.token),
                headers={"Content-Type": "application/json"},
                timeout=30,
            )
            resp.raise_for_status()
            return resp.json()
        except Exception as e:
            console.print(f"[red]Confluence API error: {e}[/red]")
            return self._simulate_page(title)

    def _simulate_page(self, title: str) -> dict[str, Any]:
        fake_id = str(abs(hash(title)) % 1000000)
        return {
            "id": fake_id,
            "title": title,
            "_links": {"webui": f"/wiki/spaces/{self.space_key}/pages/{fake_id}/{title.replace(' ', '+')}"},
        }

    def _page_url(self, result: dict[str, Any]) -> str:
        return self.url + result.get("_links", {}).get("webui", "")

    def create_project_home(self, project_name: str, client_name: str, workload_count: int) -> ConfluencePage:
        """Create the top-level project home page."""
        body = f"""
<h1>{project_name}</h1>
<p><strong>Client:</strong> {client_name} | <strong>Workloads:</strong> {workload_count} |
<strong>Generated:</strong> {datetime.now(timezone.utc).strftime('%Y-%m-%d UTC')}</p>
<p>This space contains all migration runbooks and planning artifacts generated by <strong>MigrationScout V2</strong>.</p>
<ac:structured-macro ac:name="children">
  <ac:parameter ac:name="sort">creation</ac:parameter>
</ac:structured-macro>"""

        result = self._create_page(f"{project_name} — {client_name}", body)
        page = ConfluencePage(
            page_id=result.get("id", ""),
            title=f"{project_name} — {client_name}",
            url=self._page_url(result),
            space_key=self.space_key,
            dry_run=self._dry_run,
        )
        status = "[dim](dry run)[/dim]" if self._dry_run else "[green]created[/green]"
        console.print(f"  Confluence home page {status}: {page.title}")
        return page

    def create_wave_runbook_page(
        self,
        wave_number: int,
        wave_name: str,
        workload_count: int,
        estimated_weeks: float,
        risk_level: str,
        migration_cost: float,
        monthly_savings: float,
        runbook_markdown: str,
        parent_page_id: str | None = None,
    ) -> ConfluencePage:
        """Create a Confluence page for a wave runbook."""
        title = f"Wave {wave_number}: {wave_name} — Runbook"
        risk_color = {
            "low": "#36B37E", "medium": "#FFAB00", "high": "#FF5630", "critical": "#BF2600"
        }.get(risk_level, "#666")

        body = f"""
<ac:structured-macro ac:name="info">
  <ac:rich-text-body>
    <p><strong>Wave {wave_number}: {wave_name}</strong></p>
    <ul>
      <li>Workloads: {workload_count}</li>
      <li>Estimated Duration: {estimated_weeks:.1f} weeks (P50)</li>
      <li>Risk Level: <strong style="color:{risk_color}">{risk_level.upper()}</strong></li>
      <li>Migration Cost: ${migration_cost:,.0f}</li>
      <li>Monthly Savings: ${monthly_savings:,.0f}/mo</li>
    </ul>
  </ac:rich-text-body>
</ac:structured-macro>

<h2>Runbook Content</h2>
<ac:structured-macro ac:name="code">
  <ac:parameter ac:name="language">markdown</ac:parameter>
  <ac:plain-text-body><![CDATA[{runbook_markdown[:5000]}]]></ac:plain-text-body>
</ac:structured-macro>"""

        result = self._create_page(title, body, parent_id=parent_page_id)
        page = ConfluencePage(
            page_id=result.get("id", ""),
            title=title,
            url=self._page_url(result),
            space_key=self.space_key,
            dry_run=self._dry_run,
        )
        status = "[dim](dry run)[/dim]" if self._dry_run else "[green]created[/green]"
        console.print(f"  Confluence page {status}: {title}")
        return page

    def create_tco_page(
        self,
        project_name: str,
        annual_savings: float,
        total_investment: float,
        break_even: str,
        irr_percent: float,
        parent_page_id: str | None = None,
    ) -> ConfluencePage:
        """Create a Confluence page for TCO analysis."""
        title = f"{project_name} — TCO Analysis"
        body = f"""
<h2>Financial Summary</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Annual Savings</td><td><strong>${annual_savings:,.0f}</strong></td></tr>
  <tr><td>Total Investment</td><td>${total_investment:,.0f}</td></tr>
  <tr><td>Break-even Period</td><td>{break_even}</td></tr>
  <tr><td>Internal Rate of Return (IRR)</td><td><strong>{irr_percent:.1f}%</strong></td></tr>
</table>
<p>Full Excel model available in project attachments. Generated by MigrationScout V2.</p>"""

        result = self._create_page(title, body, parent_id=parent_page_id)
        page = ConfluencePage(
            page_id=result.get("id", ""),
            title=title,
            url=self._page_url(result),
            space_key=self.space_key,
            dry_run=self._dry_run,
        )
        status = "[dim](dry run)[/dim]" if self._dry_run else "[green]created[/green]"
        console.print(f"  Confluence page {status}: {title}")
        return page
