"""
ExecutiveReport — AI-Generated Board-Ready Reporting

Transforms technical analysis output into polished executive reports
formatted for non-technical stakeholders: C-suite, board members,
procurement committees.
"""

import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv()


@dataclass
class ExecutiveReport:
    title: str
    company_name: str
    generated_at: str
    executive_summary: str = ""
    key_findings: list[str] = field(default_factory=list)
    financial_impact: dict = field(default_factory=dict)
    risk_matrix: list[dict] = field(default_factory=list)
    recommendations: list[dict] = field(default_factory=list)
    next_steps: list[str] = field(default_factory=list)
    html_content: str = ""
    
    def save_html(self, path: str | Path = None) -> Path:
        output_path = Path(path or f"output/{self.company_name}_report.html")
        output_path.parent.mkdir(exist_ok=True)
        output_path.write_text(self.html_content)
        return output_path
    
    def print_summary(self):
        from rich.console import Console
        from rich.panel import Panel
        console = Console()
        console.print(Panel(self.executive_summary, title=f"[bold]{self.title}", border_style="purple"))
        
        if self.key_findings:
            console.print("\n[bold]Key Findings:")
            for f in self.key_findings:
                console.print(f"  • {f}")
        
        if self.financial_impact:
            console.print(f"\n[bold]Financial Impact:")
            for k, v in self.financial_impact.items():
                console.print(f"  {k}: {v}")


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }}
  .header {{ border-bottom: 3px solid #0066cc; padding-bottom: 20px; margin-bottom: 30px; }}
  .header h1 {{ font-size: 28px; color: #0066cc; margin: 0; }}
  .header p {{ color: #666; margin: 5px 0 0; }}
  .score-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 30px 0; }}
  .score-card {{ background: #f8f9fa; border-radius: 8px; padding: 20px; text-align: center; border-left: 4px solid #0066cc; }}
  .score-card .number {{ font-size: 48px; font-weight: bold; color: #0066cc; }}
  .score-card .label {{ font-size: 14px; color: #666; margin-top: 5px; }}
  .section {{ margin: 30px 0; }}
  .section h2 {{ font-size: 20px; border-bottom: 1px solid #eee; padding-bottom: 10px; }}
  .finding {{ padding: 12px; margin: 8px 0; border-radius: 6px; }}
  .finding.critical {{ background: #fff0f0; border-left: 4px solid #cc0000; }}
  .finding.high {{ background: #fff8f0; border-left: 4px solid #ff6600; }}
  .finding.medium {{ background: #fffef0; border-left: 4px solid #ffaa00; }}
  .recommendation {{ background: #f0f8ff; border-left: 4px solid #0066cc; padding: 12px; margin: 8px 0; border-radius: 6px; }}
  .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #eee; }}
  th {{ background: #f8f9fa; font-weight: 600; }}
</style>
</head>
<body>
{body}
<div class="footer">Generated by Enterprise AI Accelerator | {generated_at} | Powered by Claude</div>
</body>
</html>
"""


class ReportGenerator:
    """
    Generates executive-ready reports from technical analysis output.
    """
    
    SYSTEM_PROMPT = """You are a management consultant who specializes in translating technical cloud 
assessments into executive-ready communications. You write for C-suite and board audiences who 
need clear ROI, risk framing, and actionable recommendations.

Your reports:
1. Lead with financial impact (cost savings, risk reduction, revenue protection)
2. Frame technical findings in business terms
3. Use the Pyramid Principle: conclusion first, then supporting evidence
4. Quantify everything possible
5. Provide a clear "recommended next step" that's easy to approve

You respond in valid JSON only."""
    
    def __init__(self, model: Optional[str] = None):
        self.client = anthropic.Anthropic(
            api_key=os.getenv("ANTHROPIC_API_KEY")
        )
        self.model = model or os.getenv("CLAUDE_MODEL", "claude-opus-4-6")
    
    def generate(self, 
                 data: dict,
                 company_name: str = "Client",
                 audience: str = "executive",
                 cloudiq_result=None,
                 migration_plan=None,
                 compliance_result=None) -> ExecutiveReport:
        """
        Generate an executive report from analysis data.
        
        Args:
            data: Dict with any combination of analysis results
            company_name: Client company name for the report
            audience: board, executive, ciso, or cto
            cloudiq_result: Optional CloudIQ AnalysisResult
            migration_plan: Optional MigrationPlan
            compliance_result: Optional ComplianceResult
        
        Returns:
            ExecutiveReport with HTML content ready to share
        """
        # Build input from whatever we have
        combined_data = dict(data)
        
        if cloudiq_result:
            combined_data["architecture_analysis"] = {
                "security_score": cloudiq_result.security_score,
                "cost_waste_monthly": cloudiq_result.cost_waste_monthly,
                "critical_findings": cloudiq_result.critical_findings,
                "recommendations": cloudiq_result.recommendations
            }
        
        if migration_plan:
            combined_data["migration_plan"] = {
                "total_workloads": len(migration_plan.workloads) if migration_plan.workloads else 0,
                "total_effort_weeks": migration_plan.total_effort_weeks,
                "estimated_duration_months": migration_plan.estimated_duration_months,
                "quick_wins": migration_plan.quick_wins[:3],
                "blockers": migration_plan.migration_blockers
            }
        
        if compliance_result:
            combined_data["compliance"] = {
                "score": compliance_result.compliance_score,
                "critical_violations": len(compliance_result.critical_violations),
                "frameworks": compliance_result.frameworks_checked
            }
        
        prompt = f"""Generate an executive report from this technical analysis data.

COMPANY: {company_name}
AUDIENCE: {audience}
DATA:
{json.dumps(combined_data, indent=2)[:5000]}

Return ONLY valid JSON:
{{
  "title": "string",
  "executive_summary": "3-4 sentences, business impact focus",
  "key_findings": ["finding1", "finding2", "finding3"],
  "financial_impact": {{
    "monthly_savings_potential": "$X,XXX",
    "annual_savings_potential": "$X,XXX",
    "risk_exposure_reduced": "$X,XXX",
    "migration_roi_months": "X months"
  }},
  "risk_matrix": [
    {{"risk": "string", "likelihood": "High|Medium|Low", "impact": "High|Medium|Low", "status": "Current|Mitigated"}}
  ],
  "recommendations": [
    {{"priority": 1, "action": "string", "effort": "Low|Medium|High", "impact": "High|Medium|Low", "timeline": "string"}}
  ],
  "next_steps": ["immediate action 1", "action 2", "action 3"]
}}"""
        
        message = self.client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=self.SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}]
        )
        
        raw = message.content[0].text
        return self._build_report(raw, company_name)
    
    def _build_report(self, raw: str, company_name: str) -> ExecutiveReport:
        try:
            clean = raw.strip()
            if clean.startswith("```"):
                clean = clean.split("```")[1]
                if clean.startswith("json"):
                    clean = clean[4:]
            
            data = json.loads(clean)
            now = datetime.now().strftime("%B %d, %Y")
            
            report = ExecutiveReport(
                title=data.get("title", "Cloud Transformation Assessment"),
                company_name=company_name,
                generated_at=now,
                executive_summary=data.get("executive_summary", ""),
                key_findings=data.get("key_findings", []),
                financial_impact=data.get("financial_impact", {}),
                risk_matrix=data.get("risk_matrix", []),
                recommendations=data.get("recommendations", []),
                next_steps=data.get("next_steps", [])
            )
            
            report.html_content = self._render_html(report, data)
            return report
        except (json.JSONDecodeError, KeyError):
            return ExecutiveReport(
                title="Assessment Report",
                company_name=company_name,
                generated_at=datetime.now().strftime("%B %d, %Y"),
                executive_summary=raw[:500],
                html_content=HTML_TEMPLATE.format(
                    title="Report",
                    body=f"<p>{raw[:1000]}</p>",
                    generated_at=datetime.now().strftime("%B %d, %Y")
                )
            )
    
    def _render_html(self, report: ExecutiveReport, data: dict) -> str:
        findings_html = ""
        for f in report.key_findings:
            findings_html += f'<div class="finding high">{f}</div>\n'
        
        recs_html = ""
        for r in sorted(report.recommendations, key=lambda x: x.get("priority", 99)):
            recs_html += f'<div class="recommendation"><strong>Priority {r.get("priority", "")}:</strong> {r.get("action", "")} <em>({r.get("timeline", "")})</em></div>\n'
        
        impact_rows = ""
        for k, v in report.financial_impact.items():
            label = k.replace("_", " ").title()
            impact_rows += f"<tr><td>{label}</td><td><strong>{v}</strong></td></tr>\n"
        
        next_steps_html = "".join([f"<li>{s}</li>" for s in report.next_steps])
        
        body = f"""
<div class="header">
  <h1>{report.title}</h1>
  <p>{report.company_name} | {report.generated_at}</p>
</div>

<div class="section">
  <h2>Executive Summary</h2>
  <p>{report.executive_summary}</p>
</div>

<div class="section">
  <h2>Financial Impact</h2>
  <table>
    <thead><tr><th>Metric</th><th>Value</th></tr></thead>
    <tbody>{impact_rows}</tbody>
  </table>
</div>

<div class="section">
  <h2>Key Findings</h2>
  {findings_html}
</div>

<div class="section">
  <h2>Recommendations</h2>
  {recs_html}
</div>

<div class="section">
  <h2>Recommended Next Steps</h2>
  <ol>{next_steps_html}</ol>
</div>
"""
        return HTML_TEMPLATE.format(
            title=report.title,
            body=body,
            generated_at=report.generated_at
        )
